### ISSUE TITLE
Error in documentation when compiling

### ISSUE THREAD

**Issue by OStevan** [epfl-lara/inox#116]
When I run `sbt clean compile` I get the following error, simillar to #97 :
```
[info] Running (fork) tut.TutMain /home/stevan/Documents/master_project/inox/src/main/doc/tutorial.md /home/stevan/Documents/master_project/inox/doc .*\.(md|markdown|txt|htm|html) -deprecation -unchecked -feature
[info] [tut] compiling: /home/stevan/Documents/master_project/inox/src/main/doc/tutorial.md
[error] WARNING: An illegal reflective access operation has occurred
[error] WARNING: Illegal reflective access by z3.Z3Wrapper (file:/home/stevan/Documents/master_project/inox/unmanaged/scalaz3-unix-64-2.12.jar) to field java.lang.ClassLoader.sys_paths
[error] WARNING: Please consider reporting this to the maintainers of z3.Z3Wrapper
[error] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[error] WARNING: All illegal access operations will be denied in a future release
[error] null
[error] java.lang.NullPointerException
[error]         at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646)
[error]         at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
[error]         at java.base/java.lang.System.loadLibrary(System.java:1870)
[error]         at z3.Z3Wrapper.loadFromJar(Z3Wrapper.java:110)
[error]         at z3.Z3Wrapper.<clinit>(Z3Wrapper.java:49)
[error]         at inox.solvers.SolverFactory$.liftedTree1$1(SolverFactory.scala:29)
[error]         at inox.solvers.SolverFactory$.hasNativeZ3$lzycompute(SolverFactory.scala:28)
[error]         at inox.solvers.SolverFactory$.hasNativeZ3(SolverFactory.scala:28)
[error]         at inox.solvers.SolverFactory$.$anonfun$fallbacks$1(SolverFactory.scala:78)
[error]         at inox.solvers.SolverFactory$.getFromName(SolverFactory.scala:100)
[error]         at inox.solvers.SolverFactory$.apply(SolverFactory.scala:356)
[error]         at inox.solvers.SolverFactory$.apply(SolverFactory.scala:364)
[error]         at inox.package$$anon$1$$anon$2.createSolver(package.scala:76)
[error]         at inox.Semantics.$anonfun$getSolver$1(Semantics.scala:31)
[error]         at inox.utils.Cache.cached(Caches.scala:14)
[error]         at inox.utils.Cache.cached$(Caches.scala:11)
[error]         at inox.utils.LruCache.cached(Caches.scala:20)
[error]         at inox.Semantics.getSolver(Semantics.scala:31)
[error]         at inox.Semantics.getSolver$(Semantics.scala:28)
[error]         at inox.package$$anon$1$$anon$2.getSolver(package.scala:65)
[error]         at inox.Program.getSolver(Program.scala:60)
[error]         at inox.Program.getSolver$(Program.scala:57)
[error]         at inox.Program$$anon$1.getSolver(Program.scala:93)
[error]         at $line22.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<init>(<console>:27)
[error]         at $line22.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<clinit>(<console>)
[error]         at $line22.$eval$.$print$lzycompute(<console>:7)
[error]         at $line22.$eval$.$print(<console>:6)
[error]         at $line22.$eval.$print(<console>)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:742)
[error]         at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1018)
[error]         at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
[error]         at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
[error]         at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
[error]         at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
[error]         at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
[error]         at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
[error]         at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
[error]         at tut.Tut$.$anonfun$interp$6(Tut.scala:56)
[error]         at tut.felix.IO$Primitive.unsafePerformIO(IO.scala:76)
[error]         at tut.felix.IO$Compute.loop$1(IO.scala:117)
[error]         at tut.felix.IO$Compute.unsafePerformIO(IO.scala:125)
[error]         at tut.felix.Syntax$IOOps.$anonfun$withOut$2(Syntax.scala:34)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at scala.Console$.withOut(Console.scala:167)
[error]         at tut.felix.Syntax$IOOps.$anonfun$withOut$1(Syntax.scala:34)
[error]         at tut.felix.IO$Primitive.unsafePerformIO(IO.scala:76)
[error]         at tut.felix.IO$Compute.loop$1(IO.scala:121)
[error]         at tut.felix.IO$Compute.unsafePerformIO(IO.scala:125)
[error]         at tut.TutMain$.main(TutMain.scala:8)
[error]         at tut.TutMain.main(TutMain.scala)
[error] [tut] *** Error reported at /home/stevan/Documents/master_project/inox/src/main/doc/tutorial.md:203
[error] java.lang.NullPointerException
[error]   at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646)
[error]   at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
[error]   at java.base/java.lang.System.loadLibrary(System.java:1870)
[error]   at com.microsoft.z3.Native.<clinit>(Native.java:13)
[error]   at z3.Z3Wrapper.z3VersionString(Z3Wrapper.java:75)
[error]   at z3.Z3Wrapper.<clinit>(Z3Wrapper.java:51)
[error]   at inox.solvers.SolverFactory$.liftedTree1$1(SolverFactory.scala:29)
[error]   at inox.solvers.SolverFactory$.hasNativeZ3$lzycompute(SolverFactory.scala:28)
[error]   at inox.solvers.SolverFactory$.hasNativeZ3(SolverFactory.scala:28)
[error]   at inox.solvers.SolverFactory$.$anonfun$fallbacks$1(SolverFactory.scala:78)
[error]   at inox.solvers.SolverFactory$.getFromName(SolverFactory.scala:100)
[error]   at inox.solvers.SolverFactory$.apply(SolverFactory.scala:356)
[error]   at inox.solvers.SolverFactory$.apply(SolverFactory.scala:364)
[error]   at inox.package$$anon$1$$anon$2.createSolver(package.scala:76)
[error]   at inox.Semantics.$anonfun$getSolver$1(Semantics.scala:31)
[error]   at inox.utils.Cache.cached(Caches.scala:14)
[error]   at inox.utils.Cache.cached$(Caches.scala:11)
[error]   at inox.utils.LruCache.cached(Caches.scala:20)
[error]   at inox.Semantics.getSolver(Semantics.scala:31)
[error]   at inox.Semantics.getSolver$(Semantics.scala:28)
[error]   at inox.package$$anon$1$$anon$2.getSolver(package.scala:65)
[error]   at inox.Program.getSolver(Program.scala:60)
[error]   at inox.Program.getSolver$(Program.scala:57)
[error]   at inox.Program$$anon$1.getSolver(Program.scala:93)
[error]   ... 31 elided
[error] [tut] *** Error reported at /home/stevan/Documents/master_project/inox/src/main/doc/tutorial.md:204
[error] <console>:28: error: not found: value solver
[error]        solver.assertCnstr(Not(prop))
[error]        ^
[error] [tut] *** Error reported at /home/stevan/Documents/master_project/inox/src/main/doc/tutorial.md:205
[error] <console>:27: error: not found: value solver
[error]        solver.check(SolverResponses.Simple) // Should return `Unsat`
[error]        ^
[error] [tut] *** Error reported at /home/stevan/Documents/master_project/inox/src/main/doc/tutorial.md:206
[error] <console>:27: error: not found: value solver
[error]        solver.free()
[error]        ^
[error] Exception in thread "main" tut.TutException: Tut execution failed.
[error]         at tut.TutMain$.$anonfun$runl$6(TutMain.scala:17)
[error]         at tut.felix.IO$Compute.loop$1(IO.scala:121)
[error]         at tut.felix.IO$Compute.unsafePerformIO(IO.scala:125)
[error]         at tut.TutMain$.main(TutMain.scala:8)
[error]         at tut.TutMain.main(TutMain.scala)
[error] java.lang.RuntimeException: Nonzero exit code returned from runner: 1
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at tut.TutPlugin$.$anonfun$tutOne$1(TutPlugin.scala:149)
[error]         at scala.util.Success.foreach(Try.scala:249)
[error]         at tut.TutPlugin$.tutOne(TutPlugin.scala:149)
[error]         at tut.TutPlugin$.$anonfun$tutAll$1(TutPlugin.scala:157)
[error]         at scala.collection.immutable.List.flatMap(List.scala:334)
[error]         at tut.TutPlugin$.tutAll(TutPlugin.scala:157)
[error]         at tut.TutPlugin$.handleUpdate$1(TutPlugin.scala:106)
[error]         at tut.TutPlugin$.$anonfun$projectSettings$29(TutPlugin.scala:111)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at tut.TutPlugin$.$anonfun$projectSettings$25(TutPlugin.scala:111)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (tutQuick) Nonzero exit code returned from runner: 1
[error] Total time: 82 s, completed May 4, 2020, 5:56:43 PM

```

**Comment by romac** [comment]
Which JDK version are you running?

**Comment by jad-hamza** [comment]
I'm having the same issue with version 11, but actually this seems to be working well with version 8

**Comment by OStevan** [comment]
I am also using version 11.

**Comment by samarion** [comment]
Is this still reproducible now that we're not using tut anymore?

**Comment by jad-hamza** [comment]
I couldn't reproduce with JDK 8 or 11

**Comment by samarion** [comment]
Then let's consider this fixed.
