### ISSUE TITLE
MatchError: String in SMTLIBTarget

### ISSUE THREAD

**Issue by MikaelMayer** [epfl-lara/inox#15]
I don't know how to solve this. I don't know why there is a pattern matching error - I checked in the source, and there is nothing but a basic pattern matching on "Implies", which if it failed, should move on to the next one. I'm using inox 1.0.1 for scala 2.11

Can you please help me with that?

```
scala.MatchError: String (of class inox.ast.Types$ADTType)
[info]   at inox.solvers.smtlib.SMTLIBTarget$class.toSMT(SMTLIBTarget.scala:356)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$3$$anon$3$underlying$.inox$solvers$smtlib$Z3Target$$super$toSMT(SolverFactory.scala:176)
[info]   at inox.solvers.smtlib.Z3Target$class.toSMT(Z3Target.scala:212)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$3$$anon$3$underlying$.toSMT(SolverFactory.scala:176)
[info]   at inox.solvers.smtlib.SMTLIBTarget$class.toSMT(SMTLIBTarget.scala:354)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$3$$anon$3$underlying$.inox$solvers$smtlib$Z3Target$$super$toSMT(SolverFactory.scala:176)
[info]   at inox.solvers.smtlib.Z3Target$class.toSMT(Z3Target.scala:212)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$3$$anon$3$underlying$.toSMT(SolverFactory.scala:176)
[info]   at inox.solvers.smtlib.SMTLIBTarget$$anonfun$toSMT$8.apply(SMTLIBTarget.scala:428)
[info]   at inox.solvers.smtlib.SMTLIBTarget$$anonfun$toSMT$8.apply(SMTLIBTarget.scala:428)
```

**Comment by MikaelMayer** [comment]
Solved thanks to @samarion 

I was using the + in the DSL which was for integers, instead of StringConcat.
