### ISSUE TITLE
String conversion problem

### ISSUE THREAD

**Issue by MikaelMayer** [epfl-lara/inox#24]
To reproduce this problem, use the following self-contained script in a console having inox:

```scala
import inox._
import inox.trees._
import inox.trees.dsl._
import inox.solvers._

val prog = InoxProgram(
  Context.empty.copy(options = Options(Seq(Main.optDebug(Set(solvers.DebugSectionSolver)), optSelectedSolvers(Set("smt-cvc4"))))), Nil, List()
)
val solver = prog.getSolver.getNewSolver
implicit class StringVars(sc: StringContext) {
  def l() = StringLiteral(sc.parts.mkString(""))
}
implicit class Cct(s: Expr) {
  def +&(other: Expr) = StringConcat(s, other)
}
val f4 = Variable(FreshIdentifier("f4"), FunctionType(Seq(StringType), StringType), Set())
val cstr = f4 === \("x"::StringType)(x => x +& l" ?")
solver.assertCnstr(cstr)
solver.check(SolverResponses.Model)
```

Although the formula is trivial, the result is unexpected:

```
java.lang.ClassCastException: inox.ast.Types$StringType$ cannot be cast to inox.ast.Types$ADTType
  at inox.ast.TreeDeconstructor$$anonfun$deconstruct$50.apply(Extractors.scala:126)
  at inox.ast.TreeDeconstructor$$anonfun$deconstruct$50.apply(Extractors.scala:126)
  at inox.ast.TreeTransformer$class.transform(TreeOps.scala:145)
  at inox.solvers.theories.ASCIIStringEncoder$decoder$.transform(ASCIIStringEncoder.scala:102)
  at inox.ast.TreeTransformer$$anonfun$3.apply(TreeOps.scala:133)
  at inox.ast.TreeTransformer$$anonfun$3.apply(TreeOps.scala:132)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:285)
  at inox.ast.TreeTransformer$class.transform(TreeOps.scala:132)
  at inox.solvers.theories.ASCIIStringEncoder$decoder$.transform(ASCIIStringEncoder.scala:102)
  at inox.ast.TreeTransformer$TreeTransformerComposition$class.transform(TreeOps.scala:238)
  at inox.ast.TreeTransformer$$anon$1.transform(TreeOps.scala:257)
  at inox.ast.TreeTransformer$TreeTransformerComposition$class.transform(TreeOps.scala:238)
  at inox.ast.TreeTransformer$$anon$1.transform(TreeOps.scala:257)
  at inox.ast.ProgramTransformer$class.decode(ProgramOps.scala:27)
  at inox.ast.ProgramTransformer$$anon$4.decode(ProgramOps.scala:46)
  at inox.solvers.unrolling.AbstractUnrollingSolver$class.decode(UnrollingSolver.scala:64)
  at inox.solvers.SolverFactory$$anonfun$getFromName$6$$anon$6.decode(SolverFactory.scala:248)
  at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$43.apply(UnrollingSolver.scala:540)
  at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$43.apply(UnrollingSolver.scala:540)
  at inox.solvers.unrolling.AbstractUnrollingSolver$ModelWrapper$$anonfun$6.apply(UnrollingSolver.scala:178)
  at inox.solvers.unrolling.AbstractUnrollingSolver$ModelWrapper$$anonfun$6.apply(UnrollingSolver.scala:178)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at inox.solvers.unrolling.AbstractUnrollingSolver$ModelWrapper$class.getModel(UnrollingSolver.scala:178)
  at inox.solvers.unrolling.UnrollingSolver$ModelWrapper.getModel(UnrollingSolver.scala:848)
  at inox.solvers.unrolling.AbstractUnrollingSolver$class.extractTotalModel(UnrollingSolver.scala:540)
  at inox.solvers.unrolling.AbstractUnrollingSolver$class.checkAssumptions(UnrollingSolver.scala:667)
  at inox.solvers.SolverFactory$$anonfun$getFromName$6$$anon$6.inox$solvers$combinators$TimeoutSolver$$super$checkAssumptions(SolverFactory.scala:248)
  at inox.solvers.combinators.TimeoutSolver$class.checkAssumptions(TimeoutSolver.scala:47)
  at inox.solvers.SolverFactory$$anonfun$getFromName$6$$anon$6.inox$tip$TipDebugger$$super$checkAssumptions(SolverFactory.scala:248)
  at inox.tip.TipDebugger$class.checkAssumptions(TipDebugger.scala:62)
  at inox.solvers.SolverFactory$$anonfun$getFromName$6$$anon$6.checkAssumptions(SolverFactory.scala:248)
  at inox.solvers.unrolling.AbstractUnrollingSolver$class.check(UnrollingSolver.scala:87)
  at inox.solvers.SolverFactory$$anonfun$getFromName$6$$anon$6.inox$solvers$combinators$TimeoutSolver$$super$check(SolverFactory.scala:248)
  at inox.solvers.combinators.TimeoutSolver$class.check(TimeoutSolver.scala:35)
  at inox.solvers.SolverFactory$$anonfun$getFromName$6$$anon$6.inox$tip$TipDebugger$$super$check(SolverFactory.scala:248)
  at inox.tip.TipDebugger$class.check(TipDebugger.scala:57)
  at inox.solvers.SolverFactory$$anonfun$getFromName$6$$anon$6.check(SolverFactory.scala:248)
```

The error is the same if I use z3 instead of CVC4.

**Comment by samarion** [comment]
Fixed in 4a939a53f4dc73f4e672989336cb6dffbc4231c2
