### ISSUE TITLE
Tests failing with Z3 4.6.0 or newer

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/inox#77]
Tests are currently not going through for me on master with Z3 4.6.0 or Z3 4.7.1. With Z3 4.5.0 they're ok. (different error than https://github.com/epfl-lara/inox/issues/57)

```
[info] - 133: size(x) > 0 is satisfiable solvr=smt-z3 lucky=false check=false assum=true assck=false model=0 *** FAILED *** (27 milliseconds)
[info]   inox.package$FatalError: Unexpected error from z3 solver: Solver encountered exception: smtlib.parser.Parser$UnexpectedTokenException: Unexpected token at position: (15, 2). Expected: [SymbolLitKind]. Found: OParen
```

**Comment by samarion** [comment]
Could someone with z3 >= 4.4.6 please try the fix I pushed at https://github.com/epfl-lara/inox/tree/z3-testers

**Comment by jad-hamza** [comment]
Not working

```
$ sbt "it:testOnly *SimpleUnrollingSuite* -- -z 133"
[info] Loading project definition from /path/inox/project
[info] Set current project to inox (in build file:/path/inox/)
[info] SimpleUnrollingSuite:
[info] - 133: size(x) > 0 is satisfiable solvr=smt-z3 lucky=false check=false assum=true assck=false model=0 *** FAILED *** (326 milliseconds)
[info]   inox.package$FatalError: Unexpected error from z3 solver: Solver encountered exception: smtlib.parser.Parser$UnexpectedTokenException: Unexpected token at position: (16, 2). Expected: [SymbolLitKind]. Found: OParen
[info]   at inox.Reporter.onFatal(Reporter.scala:39)
[info]   at inox.Reporter.fatalError(Reporter.scala:50)
[info]   at inox.Reporter.fatalError(Reporter.scala:98)
[info]   at inox.solvers.smtlib.SMTLIBTarget$class.emit(SMTLIBTarget.scala:66)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8$$anon$3.inox$solvers$smtlib$SMTLIBDebugger$$super$emit(SolverFactory.scala:211)
[info]   at inox.solvers.smtlib.SMTLIBDebugger$class.emit(SMTLIBDebugger.scala:50)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8$$anon$3.emit(SolverFactory.scala:211)
[info]   at inox.solvers.smtlib.SMTLIBSolver$class.extractResponse(SMTLIBSolver.scala:109)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8$$anon$3.inox$solvers$smtlib$Z3Solver$$super$extractResponse(SolverFactory.scala:211)
[info]   at inox.solvers.smtlib.Z3Solver$class.extractResponse(Z3Solver.scala:20)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8$$anon$3.extractResponse(SolverFactory.scala:211)
[info]   at inox.solvers.smtlib.Z3Solver$class.checkAssumptions(Z3Solver.scala:44)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8$$anon$3.checkAssumptions(SolverFactory.scala:211)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$checkAssumptions$1$$anonfun$43.apply(UnrollingSolver.scala:537)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$checkAssumptions$1$$anonfun$43.apply(UnrollingSolver.scala:537)
[info]   at scala.util.Try$.apply(Try.scala:192)
[info]   at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
[info]   at inox.utils.TimerStorage.run(Timer.scala:88)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$checkAssumptions$1.apply(UnrollingSolver.scala:536)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$checkAssumptions$1.apply(UnrollingSolver.scala:472)
[info]   at scala.util.Try$.apply(Try.scala:192)
[info]   at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
[info]   at inox.utils.TimerStorage.run(Timer.scala:88)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$class.checkAssumptions(UnrollingSolver.scala:472)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.inox$solvers$combinators$TimeoutSolver$$super$checkAssumptions(SolverFactory.scala:198)
[info]   at inox.solvers.combinators.TimeoutSolver$class.checkAssumptions(TimeoutSolver.scala:47)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.inox$tip$TipDebugger$$super$checkAssumptions(SolverFactory.scala:198)
[info]   at inox.tip.TipDebugger$class.checkAssumptions(TipDebugger.scala:61)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.checkAssumptions(SolverFactory.scala:198)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$class.check(UnrollingSolver.scala:86)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.inox$solvers$combinators$TimeoutSolver$$super$check(SolverFactory.scala:198)
[info]   at inox.solvers.combinators.TimeoutSolver$class.check(TimeoutSolver.scala:35)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.inox$tip$TipDebugger$$super$check(SolverFactory.scala:198)
[info]   at inox.tip.TipDebugger$class.check(TipDebugger.scala:56)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.check(SolverFactory.scala:198)
[info]   at inox.solvers.SimpleSolverAPI$class.solveSAT(SimpleSolverAPI.scala:35)
[info]   at inox.solvers.SimpleSolverAPI$$anon$1.solveSAT(SimpleSolverAPI.scala:57)
[info]   at inox.solvers.unrolling.SimpleUnrollingSuite$$anonfun$3.apply(SimpleUnrollingSuite.scala:51)
[info]   at inox.solvers.unrolling.SimpleUnrollingSuite$$anonfun$3.apply(SimpleUnrollingSuite.scala:47)
[info]   at inox.TestSuite$$anonfun$test$2$$anonfun$apply$2.apply$mcV$sp(TestSuite.scala:57)
[info]   at inox.TestSuite$$anonfun$test$2$$anonfun$apply$2.apply(TestSuite.scala:57)
[info]   at inox.TestSuite$$anonfun$test$2$$anonfun$apply$2.apply(TestSuite.scala:57)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
[info]   at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
[info]   at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
[info]   at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
[info]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
[info]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
[info]   at org.scalatest.FunSuite.run(FunSuite.scala:1560)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info] Run completed in 1 second, 301 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]         inox.solvers.unrolling.SimpleUnrollingSuite
[error] (it:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed 12 sept. 2018 17:29:15
```

**Comment by jad-hamza** [comment]
I ran z3 on the `smt2` file which is produced and got:

```
$ z3 z3-NA-0.smt2 
(:version "4.6.0")
unsat
((not start!1))
```

**Comment by jad-hamza** [comment]
And here is the SMT file:
```
$ cat z3-NA-0.smt2 
; Options: -in -smt2
(set-option :produce-unsat-assumptions true)

(get-info :version)

(declare-fun start!1 () Bool)

(assert start!1)

(declare-datatypes () ((List!2 (Nil!2) (Cons!2 (head!2 Int) (tail!2 List!2)))))

(declare-fun x!0 () List!2)

(declare-fun size!1 (List!2) Int)

(assert (=> start!1 (> (size!1 x!0) 0)))

(assert (=> start!1 true))

(declare-fun bs!1 () Bool)

(assert (= bs!1 start!1))

(declare-fun m!1 () Bool)

(assert (=> bs!1 m!1))

(check-sat (not start!1))
(get-unsat-assumptions)
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/inox/commit/4815673cefb8b07cf9c9a4a7d721166f8bcc7ec2 and https://github.com/epfl-lara/inox/commit/ae973e13a98e3034e1d4a147c3da405f10eb25be
