### ISSUE TITLE
StringSuite test fail with Z3 4.7.1

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/inox#81]
```
$ sbt "it:testOnly *StringSuite* -- -z 28"
[info] Loading project definition from /path/inox/project
[info] Set current project to inox (in build file:/path/inox/)
[info] StringSuite:
[info] -  28: Non-ASCII string encoding solvr=smt-z3 *** FAILED *** (472 milliseconds)
[info]   scala.MatchError: WrappedArray(-17, -65, -125) (of class scala.collection.mutable.WrappedArray$ofByte)
[info]   at inox.solvers.theories.ASCIIStringEncoder$class.inox$solvers$theories$ASCIIStringEncoder$$decodeFirstByte(ASCIIStringEncoder.scala:35)
[info]   at inox.solvers.theories.ASCIIStringEncoder$decoder$.unescape$1(ASCIIStringEncoder.scala:68)
[info]   at inox.solvers.theories.ASCIIStringEncoder$decoder$.unescape$1(ASCIIStringEncoder.scala:84)
[info]   at inox.solvers.theories.ASCIIStringEncoder$decoder$.unescape$1(ASCIIStringEncoder.scala:84)
[info]   at inox.solvers.theories.ASCIIStringEncoder$decoder$.transform(ASCIIStringEncoder.scala:87)
[info]   at inox.ast.TreeTransformer$TreeTransformerComposition$class.transform(TreeOps.scala:291)
[info]   at inox.ast.TreeTransformer$$anon$1.transform(TreeOps.scala:310)
[info]   at inox.ast.ProgramTransformer$class.decode(ProgramOps.scala:27)
[info]   at inox.ast.ProgramTransformer$$anon$4.decode(ProgramOps.scala:46)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$class.decode(UnrollingSolver.scala:63)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.decode(SolverFactory.scala:198)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$class.decodeOrSimplest$1(UnrollingSolver.scala:455)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$39.apply(UnrollingSolver.scala:461)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$39.apply(UnrollingSolver.scala:461)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$ModelWrapper$$anonfun$6.apply(UnrollingSolver.scala:184)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$ModelWrapper$$anonfun$6.apply(UnrollingSolver.scala:184)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$ModelWrapper$class.getModel(UnrollingSolver.scala:184)
[info]   at inox.solvers.unrolling.UnrollingSolver$ModelWrapper.getModel(UnrollingSolver.scala:783)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$class.inox$solvers$unrolling$AbstractUnrollingSolver$$extractTotalModel(UnrollingSolver.scala:461)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$checkAssumptions$1.apply(UnrollingSolver.scala:597)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$$anonfun$checkAssumptions$1.apply(UnrollingSolver.scala:472)
[info]   at scala.util.Try$.apply(Try.scala:192)
[info]   at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
[info]   at inox.utils.TimerStorage.run(Timer.scala:88)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$class.checkAssumptions(UnrollingSolver.scala:472)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.inox$solvers$combinators$TimeoutSolver$$super$checkAssumptions(SolverFactory.scala:198)
[info]   at inox.solvers.combinators.TimeoutSolver$class.checkAssumptions(TimeoutSolver.scala:47)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.inox$tip$TipDebugger$$super$checkAssumptions(SolverFactory.scala:198)
[info]   at inox.tip.TipDebugger$class.checkAssumptions(TipDebugger.scala:61)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.checkAssumptions(SolverFactory.scala:198)
[info]   at inox.solvers.unrolling.AbstractUnrollingSolver$class.check(UnrollingSolver.scala:86)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.inox$solvers$combinators$TimeoutSolver$$super$check(SolverFactory.scala:198)
[info]   at inox.solvers.combinators.TimeoutSolver$class.check(TimeoutSolver.scala:35)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.inox$tip$TipDebugger$$super$check(SolverFactory.scala:198)
[info]   at inox.tip.TipDebugger$class.check(TipDebugger.scala:56)
[info]   at inox.solvers.SolverFactory$$anonfun$getFromName$4$$anon$8.check(SolverFactory.scala:198)
[info]   at inox.solvers.SimpleSolverAPI$class.solveSAT(SimpleSolverAPI.scala:35)
[info]   at inox.solvers.SimpleSolverAPI$$anon$1.solveSAT(SimpleSolverAPI.scala:57)
[info]   at inox.solvers.unrolling.StringSuite$$anonfun$6.apply(StringSuite.scala:57)
[info]   at inox.solvers.unrolling.StringSuite$$anonfun$6.apply(StringSuite.scala:54)
[info]   at inox.TestSuite$$anonfun$test$2$$anonfun$apply$2.apply$mcV$sp(TestSuite.scala:57)
[info]   at inox.TestSuite$$anonfun$test$2$$anonfun$apply$2.apply(TestSuite.scala:57)
[info]   at inox.TestSuite$$anonfun$test$2$$anonfun$apply$2.apply(TestSuite.scala:57)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
[info]   at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
[info]   at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
[info]   at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
[info]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
[info]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
[info]   at org.scalatest.FunSuite.run(FunSuite.scala:1560)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info] Run completed in 1 second, 38 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]         inox.solvers.unrolling.StringSuite
[error] (it:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed 13 sept. 2018 13:41:11
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/inox/commit/e7f5332c3f7d3d6f762953abe083420fff6dd2f2

**Comment by jad-hamza** [comment]
I have no clue what happens in this commit but thanks :)
