### ISSUE TITLE
Error in documentation when executing `sbt compile`

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/inox#97]
I'm getting the following error when running `sbt compile` on Inox:

```
[info] Compiling 158 Scala sources to ~/inox/target/scala-2.12/classes ...
[info] Done compiling.
[info] Running (fork) tut.TutMain ~/inox/src/main/doc/trees.md ~/inox/doc .*\.(md|markdown|txt|htm|html) -deprecation -unchecked -feature
[info] [tut] compiling: ~/inox/src/main/doc/trees.md
[info] Running (fork) tut.TutMain ~/inox/src/main/doc/interpolations.md ~/inox/doc .*\.(md|markdown|txt|htm|html) -deprecation -unchecked -feature
[info] [tut] compiling: ~/inox/src/main/doc/interpolations.md
[error] Exception in thread "main" scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving <refinement of inox.ast.SimpleSymbols with inox.ast.Trees>
[error] java.lang.RuntimeException: Nonzero exit code returned from runner: 1
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at tut.TutPlugin$.$anonfun$tutOne$1(TutPlugin.scala:149)
[error]         at scala.util.Success.foreach(Try.scala:249)
[error]         at tut.TutPlugin$.tutOne(TutPlugin.scala:149)
[error]         at tut.TutPlugin$.$anonfun$tutAll$1(TutPlugin.scala:157)
[error]         at scala.collection.immutable.List.flatMap(List.scala:334)
[error]         at tut.TutPlugin$.tutAll(TutPlugin.scala:157)
[error]         at tut.TutPlugin$.handleUpdate$1(TutPlugin.scala:106)
[error]         at tut.TutPlugin$.$anonfun$projectSettings$29(TutPlugin.scala:111)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at tut.TutPlugin$.$anonfun$projectSettings$25(TutPlugin.scala:111)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (tutQuick) Nonzero exit code returned from runner: 1
```

**Comment by jad-hamza** [comment]
Same as https://github.com/epfl-lara/inox/issues/101

**Comment by romac** [comment]
Sorry, I didn't see you had already opened this issue.
